<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReclamStatusArchive(){

    }
}
