<?php

namespace ReclamationBundle\Repository;

/**
 * Reclamation2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reclamation2Repository extends \Doctrine\ORM\EntityRepository
{
}
