<?php

namespace CertificationBundle\Repository;

/**
 * ExamContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamContentRepository extends \Doctrine\ORM\EntityRepository
{

}
