<?php

namespace CertificationBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userId
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findTestsByUserIdWhereStatusIsActive($userId)
    {
        // we wanna select all of the tests in the Tests table where the id of the test for the current user in usersTests table
        // doesnt have status blocked.
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT T FROM CertificationBundle:Test T 
                     JOIN  CertificationBundle:UsersTests UT 
                     WITH UT.test_id = T.id_test
                     WHERE UT.user_id= :userId AND UT.status = :status1 OR UT.status = :status2 
                     '
            )->setParameter('status1', 'active')
            ->setParameter('status2', 'failed')
            ->setParameter('userId', $userId);
        return $query;
    }
}

