<?php

namespace CertificationBundle\Repository;

/**
 * UsersTestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTestsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbrEssaieAndIdTest($userId){
        $query = $this->getEntityManager()->createQuery(
            "
            SELECT UT FROM CertificationBundle:UsersTests UT
            JOIN CertificationBundle:Test T WITH UT.test_id = T.id_test 
            WHERE UT.user_id = :userId AND  UT.status = :status1 OR UT.status = :status2
            "
        )->setParameter('userId', $userId)
        ->setParameter('status1', 'active')
        ->setParameter('status2', 'failed');
        return $query->getResult();
    }
}
