services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  _defaults:
      autowire: true,
      autoconfigure: true
      # this means you cannot fetch services directly from the container via $container->get()
      # if you need to do this, you can override this setting on individual services
      public: false
  UserBundle\:

    resource: '../../*'
    autowire: true
  UserBundle\Controller\:
      resource: '../../Controller'
      autowire: true
      public: true
      tags: ['controller.service_arguments']
