<?php

namespace PostBundle\Repository;

/**
 * Demande_1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_1Repository extends \Doctrine\ORM\EntityRepository
{
}
