<?php

namespace PostBundle\Repository;

/**
 * Post_1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post_1Repository extends \Doctrine\ORM\EntityRepository
{
}
