<?php

namespace PostBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL($mot)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT v FROM PostBundle:Post v
                      WHERE v.titre_post LIKE '%".$mot."%'");
        return $q->getResult();
    }

}
